### ISSUE TITLE
Copy Prompt 

### ISSUE THREAD

**Issue by Kevanddev** [g3arshift/Space-Engineers-Mod-Manager#32]
Mod Profile Manager Menu

**Is your feature request related to a problem? Please describe.**
In "Mod Profile Manager Menu" From "Manage Mod List"
The "Copy" button/function has no confirmation prompt, limiting check, or visual feedback that a copy is created and added to the bottom of the list which can create program slowdown, and excessive memory usage when spammed clicked.

![SEMM Copy Issue](https://github.com/user-attachments/assets/8b5582e9-9110-44b1-879b-c033054869c0)

**Describe the solution you'd like**
A prompt to confirm the copy action, that both indicates a copy action is about to take place and the profile that is indicated to be copied, this would both help prevent accidental copying of profiles, and prevent excessive intentional or accidental inputs. 

Additionally it might be better if instead of adding an additional suffix "Copy" after every copy, which can become visually noisy, a counting suffix that indicates the copy counted is also added "[profile name] Copy (x)". ex. (Copy (1), Copy (2), Copy (3), etc.

**Comment by g3arshift** [comment]
This is a good enhancement, I will start work on it.

**Comment by g3arshift** [comment]
Implemented. Good feature suggestion! I also went ahead and made it so both modlists and saves use the (copy number) standard, and added pre and post operation popups to both. New build available as 0.4.2.
